#!/bin/bash                                                                     

DIRNAME=`dirname $0`
JARSHOME=$DIRNAME/target

ARTIFACT=tsk4j-armour

# The Maven version becomes part of the main jar name.  Rather than
# hard-coding it here, we locate the jar with the LATEST version. Thus
# we always run the LATEST code, should many versions be present.

JAR=`ls $JARSHOME | grep $ARTIFACT | sort -n -r | head -1`

exec java -jar target/$JAR "$@"

# eof
