# Our directory is 'x86_64', so Maven can find us (via os.arch)
# This matches the arch as known to the NativeLoader.

ARCH = x86_64

NATIVEHOME = $(abspath ../../)

-include Makefile.env

include ../Makefile
# eof

